CREATE TABLE WF_TASK (
	TASK_ID VARCHAR(32) NOT NULL,
	TASK_NAME VARCHAR(32) NOT NULL,
	CREATE_TIME VARCHAR(20) NOT NULL,
	UPDATE_TIME VARCHAR(20),
	NAME_NODE VARCHAR(50) NOT NULL,
	JOB_TRACKER VARCHAR(50) NOT NULL,
	QUEUE_NAME VARCHAR(20) NOT NULL,
	TASK_PATH VARCHAR(255) NOT NULL,
	CLUSTER_ID VARCHAR(32),
	OOZIE_URL VARCHAR(255) NOT NULL,
	CLIENT_NAME VARCHAR(255),
	TASK_TYPE VARCHAR(32),
	TASK_COORDPATH VARCHAR(255),
	START_TIME VARCHAR(32),
	END_TIME VARCHAR(32)

);
ALTER TABLE WF_TASK
    ADD CONSTRAINT WF_TASK_PK
PRIMARY KEY (TASK_ID);

CREATE TABLE WF_TASK_MAP (
	INSTANCE_ID VARCHAR(255) NOT NULL,
	TASK_ID VARCHAR(32) NOT NULL,
	CLUSTER_ID VARCHAR(32) NOT NULL,
	CLUSTER_NAME VARCHAR(255) NOT NULL,
	STATUS VARCHAR(20) NOT NULL
);
ALTER TABLE WF_TASK_MAP
    ADD CONSTRAINT WF_TASK_MAP_PK
PRIMARY KEY (INSTANCE_ID);

CREATE TABLE BDO_CLUSTERlIST(
  CLUSTERID varchar(32) NOT NULL,
  CLIENTNAME varchar(32) DEFAULT NULL,
  CLUSTERNAME varchar(255) DEFAULT NULL,
  JOBTRACKER varchar(255) DEFAULT NULL,
  NAMENODE varchar(255) DEFAULT NULL,
  OOZIEURL varchar(255) DEFAULT NULL,
  PRIMARY KEY (CLUSTERID)
)